local AddPlayerPostInit = AddPlayerPostInit
local AddPrefabPostInit = AddPrefabPostInit
local AddPrefabPostInitAny = AddPrefabPostInitAny
local AddStategraphPostInit = AddStategraphPostInit
GLOBAL.setfenv(1, GLOBAL)

--------------------------------------------------------------------------------
-------------------------------- PLAYER COMMON ---------------------------------
--------------------------------------------------------------------------------

local function TryDescribe(base_str, descstrings, modifier)
    return descstrings and (
            type(descstrings) == "string" and base_str
            or descstrings[modifier] and base_str.."."..modifier
            or descstrings.GENERIC and base_str..".GENERIC"
        )
end

local function TryCharStrings(inst, base_str, charstrings, modifier)
    if charstrings then
        base_str = base_str..".DESCRIBE."
        local character = string.upper(inst.prefab)
        return TryDescribe(base_str..character, charstrings.DESCRIBE[character], modifier)
            or TryDescribe(base_str.."PLAYER", charstrings.DESCRIBE.PLAYER, modifier)
    end
end

local function player_common_get_special_desc_fn(inst, viewer)
    local modifier = inst.components.inspectable:GetStatus(viewer) or "GENERIC"
    local character = string.upper(viewer.prefab)
    local str = character
            and TryCharStrings(inst, "CHARACTERS."..character, STRINGS.CHARACTERS[character], modifier)
            or TryCharStrings(inst, "CHARACTERS.GENERIC", STRINGS.CHARACTERS.GENERIC, modifier)
    local ret = {
        strtype = "format",
        content = str,
        params = {inst:GetDisplayName()}
    }
    return EncodeStrCode(ret)
end

AddPlayerPostInit(function(inst)
    if not TheWorld.ismastersim then return end
    if inst.components.inspectable then
        inst.components.inspectable.getspecialdescription = player_common_get_special_desc_fn
    end
end)

--------------------------------------------------------------------------------
---------------------------------- SKELETONS -----------------------------------
--------------------------------------------------------------------------------

local function skeleton_getdesc(inst, viewer)
    if inst.char and not viewer:HasTag("playerghost") then
        local mod = GetGenderStrings(inst.char)
        -- local desc = GetDescriptionCode(viewer, inst, mod)
        local char = string.upper(inst.char)
        local name = inst.playername or STRINGS.NAMES[char] and STRCODE_HEADER..".NAMES."..char
        local params = {}
        --no translations for player killer's name
        if inst.pkname then
            params = {name, inst.pkname}
            return GetDescriptionCode(viewer, inst, mod, "format", params)
        end

        --permanent translations for death cause
        if inst.cause == "unknown" then
            inst.cause = "shenanigans"
        elseif inst.cause == "moose" then
            inst.cause = math.random() < .5 and "moose1" or "moose2"
        end

        --viewer based temp translations for death cause
        local cause =
            inst.cause == "nil"
            and (viewer == "waxwell" and
                "charlie" or
                "darkness")
            or inst.cause

        local caus = string.upper(cause)
        params = {name, STRCODE_HEADER .. "NAMES.".. (STRINGS.NAMES[caus] and caus or "SHENANIGANS")}
        return GetDescriptionCode(viewer, inst, mod, "format", params)
    end
end

AddPrefabPostInit("skeleton_player", function(inst)
    if not TheWorld.ismastersim then return end

    local SetSkeletonDescription = inst.SetSkeletonDescription
    inst.SetSkeletonDescription = function(...)
        SetSkeletonDescription(...)
        inst.components.inspectable.getspecialdescription = skeleton_getdesc
    end

    local onload = inst.OnLoad
    inst.OnLoad = function(...)
        onload(...)
        if inst.components.inspectable then
            inst.components.inspectable.getspecialdescription = skeleton_getdesc
        end
    end
end)

--------------------------------------------------------------------------------
-------------------------------- SINGING SHELL ---------------------------------
--------------------------------------------------------------------------------

local NOTES =
{
    "C",
    "C#",
    "D",
    "D#",
    "E",
    "F",
    "F#",
    "G",
    "G#",
    "A",
    "A#",
    "B",
}

local function shell_getdescription(inst, viewer)
    -- return subfmt(GetDescription(viewer, inst, "GENERIC"), {note = NOTES[inst.components.cyclable.step]})
    return GetDescriptionCode(viewer, inst, "GENERIC", "subfmt", {note = NOTES[inst.components.cyclable.step]})
end

local shells = {
    "singingshell_octave5",
    "singingshell_octave4",
    "singingshell_octave3",
}

local function shell_postinit(inst)
    if not TheWorld.ismastersim then return end
    inst.components.inspectable.descriptionfn = shell_getdescription
end

for _, prefab in ipairs(shells) do
    AddPrefabPostInit(prefab, shell_postinit)
end

--------------------------------------------------------------------------------
--------------------------------- DEATH EVENT ----------------------------------
--------------------------------------------------------------------------------

-- local EventAnnouncer = require("widgets/eventannouncer")
require("widgets/eventannouncer")
function GetNewDeathAnnouncementString(theDead, source, pkname, sourceispet)
    if not theDead or not source then return "" end

    -- local message = ""
    local msg_tab = {
        strtype = "format",
        content = {},
        params = {}
    }
    if source and not theDead:HasTag("playerghost") then
        if pkname ~= nil then
            local petname = sourceispet and STRINGS.NAMES[string.upper(source)] or nil
            if petname ~= nil then
                msg_tab.content = {
                    "$%s ",
                    "UI.HUD.DEATH_ANNOUNCEMENT_1",
                    "$ ",
                    "UI.HUD.DEATH_PET_NAME",
                }
                msg_tab.params = {
                    theDead:GetDisplayName(),
                    STRCODE_HEADER .. "NAMES." .. string.upper(source)
                }
                -- theDead:GetDisplayName().." "..STRINGS.UI.HUD.DEATH_ANNOUNCEMENT_1.." "..string.format(STRINGS.UI.HUD.DEATH_PET_NAME, pkname, petname)
            else
                msg_tab.content = {
                    "$%s ",
                    "UI.HUD.DEATH_ANNOUNCEMENT_1",
                    "$ %s",
                }
                msg_tab.params = {
                    theDead:GetDisplayName(),
                    pkname
                }
                -- message = theDead:GetDisplayName().." "..STRINGS.UI.HUD.DEATH_ANNOUNCEMENT_1.." "..pkname
            end
        elseif table.contains(GetActiveCharacterList(), source) then
            msg_tab.content = {
                "$%s ",
                "UI.HUD.DEATH_ANNOUNCEMENT_1",
                "$ %s",
            }
            msg_tab.params = {
                theDead:GetDisplayName(),
                FirstToUpper(source)
            }
            -- message = theDead:GetDisplayName().." "..STRINGS.UI.HUD.DEATH_ANNOUNCEMENT_1.." "..FirstToUpper(source)
        else
            source = string.upper(source)
            if source == "NIL" then
                if theDead == "WAXWELL" then
                    source = "CHARLIE"
                else
                    source = "DARKNESS"
                end
            elseif source == "UNKNOWN" then
                source = "SHENANIGANS"
            elseif source == "MOOSE" then
                if math.random() < .5 then
                    source = "MOOSE1"
                else
                    source = "MOOSE2"
                end
            end
            msg_tab.content = {
                "$%s ",
                "UI.HUD.DEATH_ANNOUNCEMENT_1",
                "$ %s",
            }
            msg_tab.params = {
                theDead:GetDisplayName(),
                STRCODE_HEADER .. "NAMES." .. (STRINGS.NAMES[source] and source or "SHENANIGANS")
            }
            -- source = source and STRINGS.NAMES[source] or STRINGS.NAMES.SHENANIGANS
            -- message = theDead:GetDisplayName().." "..STRINGS.UI.HUD.DEATH_ANNOUNCEMENT_1.." "..source
        end

        if not theDead.ghostenabled then
            table.insert(msg_tab.content, "$.")
            -- message = message.."."
        else
            local gender = GetGenderStrings(theDead.prefab)
            if STRINGS.UI.HUD["DEATH_ANNOUNCEMENT_2_"..gender] then
                table.insert(msg_tab.content, "UI.HUD.DEATH_ANNOUNCEMENT_2_"..gender)
                -- message = message..STRINGS.UI.HUD["DEATH_ANNOUNCEMENT_2_"..gender]
            else
                table.insert(msg_tab.content, "UI.HUD.DEATH_ANNOUNCEMENT_2_DEFAULT")
                -- message = message..STRINGS.UI.HUD.DEATH_ANNOUNCEMENT_2_DEFAULT
            end
        end
    else
        local gender = GetGenderStrings(theDead.prefab)

        if STRINGS.UI.HUD["GHOST_DEATH_ANNOUNCEMENT_"..gender] then
            msg_tab.content = {
                "$%s ",
                "UI.HUD.GHOST_DEATH_ANNOUNCEMENT_" .. gender,
            }
            msg_tab.params = {
                theDead:GetDisplayName()
            }
            -- message = theDead:GetDisplayName().." "..STRINGS.UI.HUD["GHOST_DEATH_ANNOUNCEMENT_"..gender]
        else
            msg_tab.content = {
                "$%s ",
                "UI.HUD.GHOST_DEATH_ANNOUNCEMENT_DEFAULT",
            }
            msg_tab.params = {
                theDead:GetDisplayName()
            }
            -- message = theDead:GetDisplayName().." "..STRINGS.UI.HUD.GHOST_DEATH_ANNOUNCEMENT_DEFAULT
        end
    end

    return EncodeStrCode(msg_tab)
end


local STRCODE_REVIERS = {}
STRCODE_REVIERS[STRINGS.NAMES.POCKETWATCH_REVIVE] = "NAMES.POCKETWATCH_REVIVE"
STRCODE_REVIERS[STRINGS.NAMES.POCKETWATCH_REVIVE_REVIVER] = "NAMES.POCKETWATCH_REVIVE_REVIVER"
STRCODE_REVIERS[STRINGS.NAMES.AMULET] = "NAMES.AMULET"
STRCODE_REVIERS[STRINGS.NAMES.RESURRECTIONSTONE] = "NAMES.RESURRECTIONSTONE"
STRCODE_REVIERS[STRINGS.NAMES.RESURRECTIONSTATUE] = "NAMES.RESURRECTIONSTATUE"
STRCODE_REVIERS[STRINGS.NAMES.MULTIPLAYER_PORTAL] = "NAMES.MULTIPLAYER_PORTAL"
STRCODE_REVIERS[STRINGS.NAMES.MULTIPLAYER_PORTAL_MOONROCK] = "NAMES.MULTIPLAYER_PORTAL_MOONROCK"
STRCODE_REVIERS[STRINGS.NAMES.MULTIPLAYER_PORTAL_MOONROCK_CONSTR_PLANS] = "NAMES.MULTIPLAYER_PORTAL_MOONROCK_CONSTR_PLANS"

function GetNewRezAnnouncementString(theRezzed, source)
    if not theRezzed or not source then return "" end
    local strcode_source = source == STRINGS.NAMES.SHENANIGANS and STRCODE_HEADER .. "NAMES.SHENANIGANS"
            or STRCODE_REVIERS[source] and STRCODE_HEADER .. STRCODE_REVIERS[source]
            or source
    print("GetNewRezAnnouncementString", strcode_source)
    -- local message = theRezzed:GetDisplayName().." "..STRINGS.UI.HUD.REZ_ANNOUNCEMENT.." "..source.."."
    local msg_tab = {
        strtype = "format",
        content = {
            "$%s ",
            "UI.HUD.REZ_ANNOUNCEMENT",
            "$ %s."
        },
        params = {
            theRezzed:GetDisplayName(),
            strcode_source
        }
    }
    -- return message
    return EncodeStrCode(msg_tab)
end

--------------------------------------------------------------------------------
--------------------------------- MOD OUTDATE ----------------------------------
--------------------------------------------------------------------------------

-- local Networking_ModOutOfDateAnnouncement = Networking_ModOutOfDateAnnouncement
-- function Networking_ModOutOfDateAnnouncement(mod)
--     local ret = {
--         strtype = "format",
--         content = IsRail() and "MODS.VERSIONING.OUT_OF_DATE_RAIL" or "MODS.VERSIONING.OUT_OF_DATE",
--         params = {
--             mod
--         }
--     }

--     Networking_Announcement(EncodeStrCode(ret), nil , "mod")
-- end

--------------------------------------------------------------------------------
---------------------------------- TERRARIUM -----------------------------------
--------------------------------------------------------------------------------

STRCODE_ANNOUNCE[STRINGS.EYEOFTERROR_CANCEL] = "EYEOFTERROR_CANCEL"
STRCODE_ANNOUNCE[STRINGS.EYEOFTERROR_COMING] = "EYEOFTERROR_COMING"
STRCODE_ANNOUNCE[STRINGS.TWINS_COMING] = "TWINS_COMING"

STRCODE_SUBFMT[STRINGS.EYEOFTERROR_TARGET] = "EYEOFTERROR_TARGET"
STRCODE_SUBFMT[STRINGS.TWINS_TARGET] = "TWINS_TARGET"

--------------------------------------------------------------------------------
--------------------------------- WAGSTAFF_NPC ---------------------------------
--------------------------------------------------------------------------------

STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_START[1]] = "WAGSTAFF_NPC_START.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_START[2]] = "WAGSTAFF_NPC_START.2"

-- table.insert(STRCODE_TALKER, "WAGSTAFF_NPC_MUMBLE_1.1")
-- table.insert(STRCODE_TALKER, "WAGSTAFF_NPC_MUMBLE_1.2")
-- table.insert(STRCODE_TALKER, "WAGSTAFF_NPC_MUMBLE_1.3")
-- table.insert(STRCODE_TALKER, "WAGSTAFF_NPC_MUMBLE_1.4")

STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_THIS_WAY[1]] = "WAGSTAFF_NPC_THIS_WAY.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_THIS_WAY[2]] = "WAGSTAFF_NPC_THIS_WAY.2"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_THIS_WAY[3]] = "WAGSTAFF_NPC_THIS_WAY.3"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_NO_WAY1[1]] = "WAGSTAFF_NPC_NO_WAY1.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_NO_WAY2[1]] = "WAGSTAFF_NPC_NO_WAY2.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_NO_WAY3[1]] = "WAGSTAFF_NPC_NO_WAY3.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_NOT_THIS_TOOL[1]] = "WAGSTAFF_NPC_NOT_THIS_TOOL.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_NOT_THIS_TOOL[2]] = "WAGSTAFF_NPC_NOT_THIS_TOOL.2"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_YES_THIS_TOOL[1]] = "WAGSTAFF_NPC_YES_THIS_TOOL.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_YES_THIS_TOOL[2]] = "WAGSTAFF_NPC_YES_THIS_TOOL.2"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_TOO_BUSY[1]] = "WAGSTAFF_NPC_TOO_BUSY.1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_TOO_BUSY[2]] = "WAGSTAFF_NPC_TOO_BUSY.2"

STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_EXPERIMENT_DONE_1] = "WAGSTAFF_NPC_EXPERIMENT_DONE_1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_EXPERIMENT_DONE_2] = "WAGSTAFF_NPC_EXPERIMENT_DONE_2"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_EXPERIMENT_FAIL_1] = "WAGSTAFF_NPC_EXPERIMENT_FAIL_1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_EXPERIMENT_FAIL_2] = "WAGSTAFF_NPC_EXPERIMENT_FAIL_2"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_STORMPASS] = "WAGSTAFF_NPC_STORMPASS"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_MEETING] = "WAGSTAFF_NPC_MEETING"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_MEETING_2] = "WAGSTAFF_NPC_MEETING_2"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_MEETING_3] = "WAGSTAFF_NPC_MEETING_3"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_MEETING_4] = "WAGSTAFF_NPC_MEETING_4"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_MEETING_5] = "WAGSTAFF_NPC_MEETING_5"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_WANT_TOOL_1] = "WAGSTAFF_NPC_WANT_TOOL_1"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_WANT_TOOL_2] = "WAGSTAFF_NPC_WANT_TOOL_2"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_WANT_TOOL_3] = "WAGSTAFF_NPC_WANT_TOOL_3"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_WANT_TOOL_4] = "WAGSTAFF_NPC_WANT_TOOL_4"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_WANT_TOOL_5] = "WAGSTAFF_NPC_WANT_TOOL_5"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_CAPTURESTART] = "WAGSTAFF_NPC_CAPTURESTART"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_CAPTURESTOP] = "WAGSTAFF_NPC_CAPTURESTOP"
STRCODE_TALKER[STRINGS.WAGSTAFF_NPC_CAPTURESTOP2] = "WAGSTAFF_NPC_CAPTURESTOP2"
STRCODE_TALKER[STRINGS.WAGSTAFF_GOTTAGO1] = "WAGSTAFF_GOTTAGO1"
STRCODE_TALKER[STRINGS.WAGSTAFF_GOTTAGO2] = "WAGSTAFF_GOTTAGO2"

local function npc_strcodespeaker_postinit(inst)
    local talker = inst.components.talker
    if talker then
        talker:MakeStringCodeSpeaker()
    end
end

for _, prefab in ipairs({"wagstaff_npc", "wagstaff_npc_pstboss", "alterguardian_contained"}) do
    AddPrefabPostInit(prefab, npc_strcodespeaker_postinit)
end

--------------------------------------------------------------------------------
--------------------------------- HERMIT_CRAB ----------------------------------
--------------------------------------------------------------------------------

AddPrefabPostInit("hermitcrab", npc_strcodespeaker_postinit)

STRCODE_TALKER[STRINGS.HERMITCRAB_TALK_ONPURCHASE.LOW[1]] = "HERMITCRAB_TALK_ONPURCHASE.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_TALK_ONPURCHASE.MED[1]] = "HERMITCRAB_TALK_ONPURCHASE.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_TALK_ONPURCHASE.HIGH[1]] = "HERMITCRAB_TALK_ONPURCHASE.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_FLOWERS.LOW[1]] = "HERMITCRAB_COMPLAIN.PLANT_FLOWERS.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_FLOWERS.MED[1]] = "HERMITCRAB_COMPLAIN.PLANT_FLOWERS.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_FLOWERS.HIGH[1][1]] = "HERMITCRAB_COMPLAIN.PLANT_FLOWERS.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_FLOWERS.HIGH[1][2]] = "HERMITCRAB_COMPLAIN.PLANT_FLOWERS.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.REMOVE_JUNK.LOW[1]] = "HERMITCRAB_COMPLAIN.REMOVE_JUNK.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.REMOVE_JUNK.MED[1]] = "HERMITCRAB_COMPLAIN.REMOVE_JUNK.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.REMOVE_JUNK.HIGH[1]] = "HERMITCRAB_COMPLAIN.REMOVE_JUNK.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_BERRIES.LOW[1]] = "HERMITCRAB_COMPLAIN.PLANT_BERRIES.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_BERRIES.MED[1]] = "HERMITCRAB_COMPLAIN.PLANT_BERRIES.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_BERRIES.HIGH[1][1]] = "HERMITCRAB_COMPLAIN.PLANT_BERRIES.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.PLANT_BERRIES.HIGH[1][2]] = "HERMITCRAB_COMPLAIN.PLANT_BERRIES.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.FILL_MEATRACKS.LOW[1]] = "HERMITCRAB_COMPLAIN.FILL_MEATRACKS.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.FILL_MEATRACKS.MED[1][1]] = "HERMITCRAB_COMPLAIN.FILL_MEATRACKS.MED.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.FILL_MEATRACKS.MED[1][2]] = "HERMITCRAB_COMPLAIN.FILL_MEATRACKS.MED.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.FILL_MEATRACKS.HIGH[1]] = "HERMITCRAB_COMPLAIN.FILL_MEATRACKS.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.LOW[1][1]] = "HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.LOW[1][2]] = "HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.HIGH[1][1]] = "HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.HIGH[1][2]] = "HERMITCRAB_COMPLAIN.GIVE_HEAVY_FISH.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.LOW[1][1]] = "HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.LOW[1][2]] = "HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.HIGH[1][1]] = "HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.HIGH[1][2]] = "HERMITCRAB_COMPLAIN.GIVE_UMBRELLA.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_PUFFY_VEST.LOW[1]] = "HERMITCRAB_COMPLAIN.GIVE_PUFFY_VEST.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_PUFFY_VEST.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_PUFFY_VEST.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_PUFFY_VEST.HIGH[1]] = "HERMITCRAB_COMPLAIN.GIVE_PUFFY_VEST.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.LOW[1]] = "HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.HIGH[1][1]] = "HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.HIGH[1][2]] = "HERMITCRAB_COMPLAIN.GIVE_FLOWER_SALAD.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_WINTER.LOW[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_WINTER.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_WINTER.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_WINTER.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_WINTER.HIGH[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_WINTER.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_SUMMER.LOW[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_SUMMER.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_SUMMER.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_SUMMER.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_SUMMER.HIGH[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_SUMMER.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_SPRING.LOW[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_SPRING.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_SPRING.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_SPRING.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_SPRING.HIGH[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_SPRING.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_AUTUM.LOW[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_AUTUM.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_AUTUM.MED[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_AUTUM.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_COMPLAIN.GIVE_FISH_AUTUM.HIGH[1]] = "HERMITCRAB_COMPLAIN.GIVE_FISH_AUTUM.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.PLANT_FLOWERS.LOW[1]] = "HERMITCRAB_INVESTIGATE.PLANT_FLOWERS.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.PLANT_FLOWERS.MED[1]] = "HERMITCRAB_INVESTIGATE.PLANT_FLOWERS.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.PLANT_FLOWERS.HIGH[1]] = "HERMITCRAB_INVESTIGATE.PLANT_FLOWERS.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.PLANT_BERRIES.LOW[1]] = "HERMITCRAB_INVESTIGATE.PLANT_BERRIES.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.PLANT_BERRIES.MED[1]] = "HERMITCRAB_INVESTIGATE.PLANT_BERRIES.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.PLANT_BERRIES.HIGH[1]] = "HERMITCRAB_INVESTIGATE.PLANT_BERRIES.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.FILL_MEATRACKS.LOW[1]] = "HERMITCRAB_INVESTIGATE.FILL_MEATRACKS.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.FILL_MEATRACKS.MED[1]] = "HERMITCRAB_INVESTIGATE.FILL_MEATRACKS.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.FILL_MEATRACKS.HIGH[1]] = "HERMITCRAB_INVESTIGATE.FILL_MEATRACKS.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.REMOVE_LUREPLANT.LOW[1]] = "HERMITCRAB_INVESTIGATE.REMOVE_LUREPLANT.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.REMOVE_LUREPLANT.MED[1]] = "HERMITCRAB_INVESTIGATE.REMOVE_LUREPLANT.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INVESTIGATE.REMOVE_LUREPLANT.HIGH[1]] = "HERMITCRAB_INVESTIGATE.REMOVE_LUREPLANT.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[0][1]] = "HERMITCRAB_GREETING.0.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[0][2]] = "HERMITCRAB_GREETING.0.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[0][3]] = "HERMITCRAB_GREETING.0.3"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[0][4]] = "HERMITCRAB_GREETING.0.4"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[0][5]] = "HERMITCRAB_GREETING.0.5"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[1][1]] = "HERMITCRAB_GREETING.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[1][2]] = "HERMITCRAB_GREETING.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[2][1]] = "HERMITCRAB_GREETING.2.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[2][2]] = "HERMITCRAB_GREETING.2.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[3][1]] = "HERMITCRAB_GREETING.3.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[3][2]] = "HERMITCRAB_GREETING.3.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[3][3]] = "HERMITCRAB_GREETING.3.3"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[4][1][1]] = "HERMITCRAB_GREETING.4.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[4][1][2]] = "HERMITCRAB_GREETING.4.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[4][2]] = "HERMITCRAB_GREETING.4.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[5][1]] = "HERMITCRAB_GREETING.5.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[5][2][1]] = "HERMITCRAB_GREETING.5.2.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[5][2][2]] = "HERMITCRAB_GREETING.5.2.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[6][1]] = "HERMITCRAB_GREETING.6.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[7][1]] = "HERMITCRAB_GREETING.7.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[7][2]] = "HERMITCRAB_GREETING.7.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[7][3]] = "HERMITCRAB_GREETING.7.3"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[8][1]] = "HERMITCRAB_GREETING.8.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[9][1]] = "HERMITCRAB_GREETING.9.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[9][2][1]] = "HERMITCRAB_GREETING.9.2.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[9][2][2]] = "HERMITCRAB_GREETING.9.2.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[10][1]] = "HERMITCRAB_GREETING.10.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[10][2]] = "HERMITCRAB_GREETING.10.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GREETING[10][3]] = "HERMITCRAB_GREETING.10.3"

STRCODE_TALKER[STRINGS.HERMITCRAB_DEFAULT_REWARD.LOW[1][1]] = "HERMITCRAB_DEFAULT_REWARD.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_DEFAULT_REWARD.LOW[1][2]] = "HERMITCRAB_DEFAULT_REWARD.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_DEFAULT_REWARD.MED[1]] = "HERMITCRAB_DEFAULT_REWARD.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_DEFAULT_REWARD.HIGH[1]] = "HERMITCRAB_DEFAULT_REWARD.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_GROUP_REWARD.LOW[1][1]] = "HERMITCRAB_GROUP_REWARD.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GROUP_REWARD.LOW[1][2]] = "HERMITCRAB_GROUP_REWARD.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GROUP_REWARD.MED[1]] = "HERMITCRAB_GROUP_REWARD.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GROUP_REWARD.HIGH[1][1]] = "HERMITCRAB_GROUP_REWARD.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GROUP_REWARD.HIGH[1][2]] = "HERMITCRAB_GROUP_REWARD.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_INTRODUCE[1][1]] = "HERMITCRAB_INTRODUCE.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_INTRODUCE[1][2]] = "HERMITCRAB_INTRODUCE.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_1.LOW[1]] = "HERMITCRAB_REWARD.FIX_HOUSE_1.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_1.MED[1]] = "HERMITCRAB_REWARD.FIX_HOUSE_1.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_1.HIGH[1]] = "HERMITCRAB_REWARD.FIX_HOUSE_1.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_2.LOW[1]] = "HERMITCRAB_REWARD.FIX_HOUSE_2.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_2.MED[1]] = "HERMITCRAB_REWARD.FIX_HOUSE_2.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_2.HIGH[1]] = "HERMITCRAB_REWARD.FIX_HOUSE_2.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_3.LOW[1]] = "HERMITCRAB_REWARD.FIX_HOUSE_3.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_3.MED[1][1]] = "HERMITCRAB_REWARD.FIX_HOUSE_3.MED.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_3.MED[1][2]] = "HERMITCRAB_REWARD.FIX_HOUSE_3.MED.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_3.HIGH[1][1]] = "HERMITCRAB_REWARD.FIX_HOUSE_3.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_3.HIGH[1][2]] = "HERMITCRAB_REWARD.FIX_HOUSE_3.HIGH.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FIX_HOUSE_3.HIGH[1][3]] = "HERMITCRAB_REWARD.FIX_HOUSE_3.HIGH.1.3"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_FLOWERS.LOW[1]] = "HERMITCRAB_REWARD.PLANT_FLOWERS.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_FLOWERS.MED[1]] = "HERMITCRAB_REWARD.PLANT_FLOWERS.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_FLOWERS.HIGH[1]] = "HERMITCRAB_REWARD.PLANT_FLOWERS.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_JUNK.LOW[1]] = "HERMITCRAB_REWARD.REMOVE_JUNK.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_JUNK.MED[1]] = "HERMITCRAB_REWARD.REMOVE_JUNK.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_JUNK.HIGH[1][1]] = "HERMITCRAB_REWARD.REMOVE_JUNK.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_JUNK.HIGH[1][2]] = "HERMITCRAB_REWARD.REMOVE_JUNK.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_BERRIES.LOW[1][1]] = "HERMITCRAB_REWARD.PLANT_BERRIES.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_BERRIES.LOW[1][2]] = "HERMITCRAB_REWARD.PLANT_BERRIES.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_BERRIES.MED[1]] = "HERMITCRAB_REWARD.PLANT_BERRIES.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_BERRIES.HIGH[1][1]] = "HERMITCRAB_REWARD.PLANT_BERRIES.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.PLANT_BERRIES.HIGH[1][2]] = "HERMITCRAB_REWARD.PLANT_BERRIES.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FILL_MEATRACKS.LOW[1]] = "HERMITCRAB_REWARD.FILL_MEATRACKS.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FILL_MEATRACKS.MED[1]] = "HERMITCRAB_REWARD.FILL_MEATRACKS.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.FILL_MEATRACKS.HIGH[1]] = "HERMITCRAB_REWARD.FILL_MEATRACKS.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_HEAVY_FISH.LOW[1][1]] = "HERMITCRAB_REWARD.GIVE_HEAVY_FISH.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_HEAVY_FISH.LOW[1][2]] = "HERMITCRAB_REWARD.GIVE_HEAVY_FISH.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_HEAVY_FISH.MED[1]] = "HERMITCRAB_REWARD.GIVE_HEAVY_FISH.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_HEAVY_FISH.HIGH[1][1]] = "HERMITCRAB_REWARD.GIVE_HEAVY_FISH.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_HEAVY_FISH.HIGH[1][2]] = "HERMITCRAB_REWARD.GIVE_HEAVY_FISH.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_LUREPLANT.LOW[1][1]] = "HERMITCRAB_REWARD.REMOVE_LUREPLANT.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_LUREPLANT.LOW[1][2]] = "HERMITCRAB_REWARD.REMOVE_LUREPLANT.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_LUREPLANT.MED[1]] = "HERMITCRAB_REWARD.REMOVE_LUREPLANT.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_LUREPLANT.HIGH[1][1]] = "HERMITCRAB_REWARD.REMOVE_LUREPLANT.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.REMOVE_LUREPLANT.HIGH[1][2]] = "HERMITCRAB_REWARD.REMOVE_LUREPLANT.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_UMBRELLA.LOW[1]] = "HERMITCRAB_REWARD.GIVE_UMBRELLA.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_UMBRELLA.MED[1]] = "HERMITCRAB_REWARD.GIVE_UMBRELLA.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_UMBRELLA.HIGH[1]] = "HERMITCRAB_REWARD.GIVE_UMBRELLA.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_PUFFY_VEST.LOW[1]] = "HERMITCRAB_REWARD.GIVE_PUFFY_VEST.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_PUFFY_VEST.MED[1]] = "HERMITCRAB_REWARD.GIVE_PUFFY_VEST.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_PUFFY_VEST.HIGH[1]] = "HERMITCRAB_REWARD.GIVE_PUFFY_VEST.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.LOW[1]] = "HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.MED[1]] = "HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.HIGH[1][1]] = "HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.HIGH[1][2]] = "HERMITCRAB_REWARD.GIVE_FLOWER_SALAD.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_WINTER.LOW[1]] = "HERMITCRAB_REWARD.GIVE_FISH_WINTER.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_WINTER.MED[1]] = "HERMITCRAB_REWARD.GIVE_FISH_WINTER.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_WINTER.HIGH[1]] = "HERMITCRAB_REWARD.GIVE_FISH_WINTER.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_SUMMER.LOW[1]] = "HERMITCRAB_REWARD.GIVE_FISH_SUMMER.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_SUMMER.MED[1]] = "HERMITCRAB_REWARD.GIVE_FISH_SUMMER.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_SUMMER.HIGH[1]] = "HERMITCRAB_REWARD.GIVE_FISH_SUMMER.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_SPRING.LOW[1]] = "HERMITCRAB_REWARD.GIVE_FISH_SPRING.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_SPRING.MED[1]] = "HERMITCRAB_REWARD.GIVE_FISH_SPRING.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_SPRING.HIGH[1]] = "HERMITCRAB_REWARD.GIVE_FISH_SPRING.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_AUTUM.LOW[1]] = "HERMITCRAB_REWARD.GIVE_FISH_AUTUM.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_AUTUM.MED[1]] = "HERMITCRAB_REWARD.GIVE_FISH_AUTUM.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REWARD.GIVE_FISH_AUTUM.HIGH[1]] = "HERMITCRAB_REWARD.GIVE_FISH_AUTUM.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_1[1][1]] = "HERMITCRAB_STORE_UNLOCK_1.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_1[1][2]] = "HERMITCRAB_STORE_UNLOCK_1.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_2[1][1]] = "HERMITCRAB_STORE_UNLOCK_2.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_2[1][2]] = "HERMITCRAB_STORE_UNLOCK_2.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_3[1][1]] = "HERMITCRAB_STORE_UNLOCK_3.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_3[1][2]] = "HERMITCRAB_STORE_UNLOCK_3.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_4[1][1]] = "HERMITCRAB_STORE_UNLOCK_4.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_4[1][2]] = "HERMITCRAB_STORE_UNLOCK_4.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_5[1][1]] = "HERMITCRAB_STORE_UNLOCK_5.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_STORE_UNLOCK_5[1][2]] = "HERMITCRAB_STORE_UNLOCK_5.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_PLANTED_LUREPLANT_DIED.LOW[1]] =  "HERMITCRAB_PLANTED_LUREPLANT_DIED.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_PLANTED_LUREPLANT_DIED.MED[1]] =  "HERMITCRAB_PLANTED_LUREPLANT_DIED.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_PLANTED_LUREPLANT_DIED.HIGH[1]] = "HERMITCRAB_PLANTED_LUREPLANT_DIED.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_GO_HOME[1]] = "HERMITCRAB_GO_HOME.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_PANIC[1]] = "HERMITCRAB_PANIC.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_PANICHAUNT[1]] = "HERMITCRAB_PANICHAUNT.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_PANICFIRE[1]] = "HERMITCRAB_PANICFIRE.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_FIGHT[1][1]] = "HERMITCRAB_FIGHT.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_FIGHT[1][2]] = "HERMITCRAB_FIGHT.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_ATTEMPT_TRADE.LOW[1]] =  "HERMITCRAB_ATTEMPT_TRADE.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ATTEMPT_TRADE.MED[1]] =  "HERMITCRAB_ATTEMPT_TRADE.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ATTEMPT_TRADE.HIGH[1][1]] = "HERMITCRAB_ATTEMPT_TRADE.HIGH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ATTEMPT_TRADE.HIGH[1][2]] = "HERMITCRAB_ATTEMPT_TRADE.HIGH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_GETFISH_BIG[1]] = "HERMITCRAB_GETFISH_BIG.1"

STRCODE_SUBFMT[STRINGS.HERMITCRAB_REFUSE_SMALL_FISH[1]] = "HERMITCRAB_REFUSE_SMALL_FISH.1"
STRCODE_SUBFMT[STRINGS.HERMITCRAB_REFUSE_SMALL_FISH[2]] = "HERMITCRAB_REFUSE_SMALL_FISH.2"
STRCODE_SUBFMT[STRINGS.HERMITCRAB_REFUSE_SMALL_FISH[3]] = "HERMITCRAB_REFUSE_SMALL_FISH.3"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_SALAD[1][1]] = "HERMITCRAB_REFUSE_SALAD.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_SALAD[1][2]] = "HERMITCRAB_REFUSE_SALAD.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_ICE_HOT[1]] = "HERMITCRAB_REFUSE_ICE_HOT.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_ICE_HAD[1]] = "HERMITCRAB_REFUSE_ICE_HAD.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_UMBRELLA[1]] = "HERMITCRAB_REFUSE_UMBRELLA.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_UMBRELLA_HASONE[1]] = "HERMITCRAB_REFUSE_UMBRELLA_HASONE.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_COAT[1]] = "HERMITCRAB_REFUSE_COAT.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_COAT_HASONE[1]] = "HERMITCRAB_REFUSE_COAT_HASONE.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_REFUSE_VEST[1]] = "HERMITCRAB_REFUSE_VEST.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_ROYALTY[1]] = "HERMITCRAB_ANNOUNCE_ROYALTY.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_ROYALTY[2]] = "HERMITCRAB_ANNOUNCE_ROYALTY.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_ROYALTY[3]] = "HERMITCRAB_ANNOUNCE_ROYALTY.3"

STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_LINESNAP[1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_LINESNAP.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE[1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE[2]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE[3]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE.3"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE[4]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE.4"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE[5]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE.5"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE[6]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_IDLE_QUOTE.6"

STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_LINETOOLOOSE[1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_LINETOOLOOSE.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_BADCAST[1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_BADCAST.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_GOTAWAY[1][1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_GOTAWAY.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_GOTAWAY[1][2]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_GOTAWAY.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_BOTHERED.LOW[1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_BOTHERED.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_BOTHERED.MED[1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_BOTHERED.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_ANNOUNCE_OCEANFISHING_BOTHERED.HIGH[1]] = "HERMITCRAB_ANNOUNCE_OCEANFISHING_BOTHERED.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_LEVEL10_PLAYERGOOD[1]] = "HERMITCRAB_LEVEL10_PLAYERGOOD.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_LEVEL10_LOWHEALTH[1][1]] = "HERMITCRAB_LEVEL10_LOWHEALTH.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_LEVEL10_LOWHEALTH[1][2]] = "HERMITCRAB_LEVEL10_LOWHEALTH.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_LEVEL10_LOWSANITY[1][1]] = "HERMITCRAB_LEVEL10_LOWSANITY.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_LEVEL10_LOWSANITY[1][2]] = "HERMITCRAB_LEVEL10_LOWSANITY.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_LEVEL10_LOWHUNGER[1][1]] = "HERMITCRAB_LEVEL10_LOWHUNGER.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_LEVEL10_LOWHUNGER[1][2]] = "HERMITCRAB_LEVEL10_LOWHUNGER.1.2"

STRCODE_TALKER[STRINGS.HERMITCRAB_THROWBOTTLE.LOW[1][1]] = "HERMITCRAB_THROWBOTTLE.LOW.1.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_THROWBOTTLE.LOW[1][2]] = "HERMITCRAB_THROWBOTTLE.LOW.1.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_THROWBOTTLE.MED[1]] = "HERMITCRAB_THROWBOTTLE.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_THROWBOTTLE.HIGH[1]] = "HERMITCRAB_THROWBOTTLE.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_HARVESTMEAT.LOW[1]] = "HERMITCRAB_HARVESTMEAT.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_HARVESTMEAT.MED[1]] = "HERMITCRAB_HARVESTMEAT.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_HARVESTMEAT.HIGH[1]] = "HERMITCRAB_HARVESTMEAT.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_MOON_FISSURE_VENT.LOW[1]] = "HERMITCRAB_MOON_FISSURE_VENT.LOW.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_MOON_FISSURE_VENT.MED[1]] = "HERMITCRAB_MOON_FISSURE_VENT.MED.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_MOON_FISSURE_VENT.HIGH[1]] = "HERMITCRAB_MOON_FISSURE_VENT.HIGH.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_GOT_PEARL[1]] = "HERMITCRAB_GOT_PEARL.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GOT_PEARL[2]] = "HERMITCRAB_GOT_PEARL.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GOT_PEARL[3]] = "HERMITCRAB_GOT_PEARL.3"
STRCODE_TALKER[STRINGS.HERMITCRAB_GOT_PEARL[4]] = "HERMITCRAB_GOT_PEARL.4"
STRCODE_TALKER[STRINGS.HERMITCRAB_GOT_PEARL[5]] = "HERMITCRAB_GOT_PEARL.5"

STRCODE_TALKER[STRINGS.HERMITCRAB_WANT_HOUSE[1]] = "HERMITCRAB_WANT_HOUSE.1"

STRCODE_TALKER[STRINGS.HERMITCRAB_GIVE_PEARL[1]] = "HERMITCRAB_GIVE_PEARL.1"
STRCODE_TALKER[STRINGS.HERMITCRAB_GIVE_PEARL[2]] = "HERMITCRAB_GIVE_PEARL.2"
STRCODE_TALKER[STRINGS.HERMITCRAB_GIVE_PEARL[3]] = "HERMITCRAB_GIVE_PEARL.3"

--------------------------------------------------------------------------------
------------------------------- TROPHYSCALE_FISH -------------------------------
--------------------------------------------------------------------------------

local function IsHoldingItem(inst)
    return inst.components.trophyscale.item_data ~= nil and not inst:HasTag("burnt")
end

local function trophyscale_fish_getdesc(inst, viewer)
    if inst:HasTag("burnt") then
        return GetDescriptionCode(viewer, inst, "BURNT")
    elseif inst:HasTag("fire") then
        return GetDescriptionCode(viewer, inst, "BURNING")
    elseif IsHoldingItem(inst) then
        local data = inst.components.trophyscale.item_data
        local heavy_postfix =  (data.is_heavy and "_HEAVY" or "")

        if data.prefab_override_owner ~= nil then
            -- return subfmt(GetDescription(viewer, inst, "HAS_ITEM"..heavy_postfix), {weight = data.weight or "",
            --  owner = STRINGS.UI.HUD.TROPHYSCALE_PREFAB_OVERRIDE_OWNER[data.prefab_override_owner] ~= nil and STRINGS.UI.HUD.TROPHYSCALE_PREFAB_OVERRIDE_OWNER[data.prefab_override_owner]
            --  or STRINGS.UI.HUD.TROPHYSCALE_UNKNOWN_OWNER})

            return GetDescriptionCode(viewer, inst, "HAS_ITEM"..heavy_postfix, "subfmt", {weight = data.weight or "",
                owner = STRINGS.UI.HUD.TROPHYSCALE_PREFAB_OVERRIDE_OWNER[data.prefab_override_owner] ~= nil and STRCODE_HEADER .. "UI.HUD.TROPHYSCALE_PREFAB_OVERRIDE_OWNER." .. data.prefab_override_owner
                or STRCODE_HEADER .. "UI.HUD.TROPHYSCALE_UNKNOWN_OWNER"})
        else
            local name = data.owner_userid == nil and STRCODE_HEADER .. "UI.HUD.TROPHYSCALE_UNKNOWN_OWNER" or data.owner_name
            -- return data.owner_userid ~= nil and data.owner_userid == viewer.userid and subfmt(GetDescription(viewer, inst, "OWNER"..heavy_postfix), {weight = data.weight or "", owner = name or ""}) or
            --  subfmt(GetDescription(viewer, inst, "HAS_ITEM"..heavy_postfix), {weight = data.weight or "", owner = name or ""})
            return data.owner_userid ~= nil and data.owner_userid == viewer.userid
                and GetDescriptionCode(viewer, inst, "OWNER"..heavy_postfix, "subfmt", {weight = data.weight or "", owner = name or ""})
                or GetDescriptionCode(viewer, inst, "HAS_ITEM"..heavy_postfix, "subfmt", {weight = data.weight or "", owner = name or ""})
        end
    end

    return GetDescriptionCode(viewer, inst) or nil
end

AddPrefabPostInit("trophyscale_fish", function(inst)
    if not TheWorld.ismastersim then return end
    inst.components.inspectable.getspecialdescription = trophyscale_fish_getdesc

end)

--------------------------------------------------------------------------------
------------------------- TROPHYSCALE_OVERSIZEDVEGGIES -------------------------
--------------------------------------------------------------------------------

local function trophyscale_oversizedveggies_getdesc(inst, viewer)
	if inst:HasTag("burnt") then
		return GetDescriptionCode(viewer, inst, "BURNT")
	elseif inst:HasTag("fire") then
		return GetDescriptionCode(viewer, inst, "BURNING")
	elseif IsHoldingItem(inst) then
		local data = inst.components.trophyscale.item_data

		if data.weight == nil or data.weight <= 0 then
			return GetDescriptionCode(viewer, inst, "HAS_ITEM_LIGHT")
		end

		local heavy_postfix =  (data.is_heavy and "_HEAVY" or "")
		return GetDescriptionCode(viewer, inst, "HAS_ITEM"..heavy_postfix, "subfmt", {weight = data.weight or "", day = data.day or ""})
	end

	return GetDescriptionCode(viewer, inst) or nil
end

AddPrefabPostInit("trophyscale_oversizedveggies", function(inst)
    if not TheWorld.ismastersim then return end
    inst.components.inspectable.getspecialdescription = trophyscale_oversizedveggies_getdesc

end)

--------------------------------------------------------------------------------
--------------------------- YOTC_CARRAT_RACE_FINISH ----------------------------
--------------------------------------------------------------------------------


local function yotc_carrat_race_finish_getdesc(inst, viewer)
	if inst:HasTag("burnt") then
		return GetDescriptionCode(viewer, inst, "BURNT")
	elseif inst._active and inst._winner ~= nil then
		if inst._winner.userid ~= nil and inst._winner.userid == viewer.userid then
			return GetDescriptionCode(viewer, inst, "I_WON")
		elseif inst._winner.name ~= nil then
			return GetDescriptionCode(viewer, inst, "SOMEONE_ELSE_WON", "subfmt", { winner = inst._winner.name })
		end
	end

	return GetDescriptionCode(viewer, inst) or nil
end

AddPrefabPostInit("yotc_carrat_race_finish", function(inst)
    if not TheWorld.ismastersim then return end
    inst.components.inspectable.getspecialdescription = yotc_carrat_race_finish_getdesc

end)

--------------------------------------------------------------------------------
------------------------------- USE_POCKET_SCALE -------------------------------
--------------------------------------------------------------------------------

AddStategraphPostInit("wilson", function(self)
    -- local onenter = self.states["use_pocket_scale"].onenter
    self.states["use_pocket_scale"].timeline[1] =

        TimeEvent(30 * FRAMES, function(inst)
            local weight = inst.sg.statemem.target ~= nil and inst.sg.statemem.target.components.weighable:GetWeight() or nil
            if weight ~= nil and inst:PerformBufferedAction() then
                local announce_str = inst.sg.statemem.target.components.weighable:GetWeightPercent() >= TUNING.WEIGHABLE_HEAVY_WEIGHT_PERCENT and "ANNOUNCE_WEIGHT_HEAVY" or "ANNOUNCE_WEIGHT"
                local str = GetStringCode(inst, announce_str, nil, "subfmt", {weight = string.format("%0.2f", weight)})
                inst.components.talker:Say(str)
            else
                inst.AnimState:ClearOverrideBuild(inst.sg.statemem.target_build)
                inst:ClearBufferedAction()
                inst.AnimState:SetTime(51 * FRAMES)
            end
        end)

end)

--------------------------------------------------------------------------------
---------------------------------- BLUEPRINT -----------------------------------
--------------------------------------------------------------------------------

local function get_blueprint_string_ret(inst)
    local ret = inst.is_rare
        and {
            strtype = "subfmt",
            content = "NAMES.BLUEPRINT_RARE",
            params = { item = STRINGS.NAMES[string.upper(inst.recipetouse)] and STRCODE_HEADER .. "NAMES." .. string.upper(inst.recipetouse) or STRCODE_HEADER .. "NAMES.UNKNOWN" }
        }

        or {
            content = {
                -- "$angri ", -- Test String
                STRINGS.NAMES[string.upper(inst.recipetouse)] and "NAMES." .. string.upper(inst.recipetouse) or "NAMES.UNKNOWN",
                "$ ",
                "NAMES.BLUEPRINT"
            }
        }

    return EncodeStrCode(ret)
end

local function blueprint_postinit(inst)
    if not TheWorld.ismastersim then return end

    inst.components.named:SetName(get_blueprint_string_ret(inst))

    local onload = inst.OnLoad
    inst.OnLoad = function(inst, data)
        onload(inst, data)
        inst.components.named:SetName(get_blueprint_string_ret(inst))
        inst.drawnameoverride = get_blueprint_string_ret(inst)
    end

    local onhaunt = inst.components.hauntable.onhaunt
    inst.components.hauntable:SetOnHauntFn(function(self, ...)
        onhaunt(self, ...)
        inst.components.named:SetName(get_blueprint_string_ret(inst))
        inst.drawnameoverride = get_blueprint_string_ret(inst)
    end)

    inst.drawnameoverride = get_blueprint_string_ret(inst)
end

AddPrefabPostInit("blueprint", blueprint_postinit)

--------------------------------------------------------------------------------
----------------------------------- MINISIGN -----------------------------------
--------------------------------------------------------------------------------

local function minisign_displaynamefn(inst)
    return #inst._imagename:value() > 0
        and subfmt(STRINGS.NAMES.MINISIGN_DRAWN, { item = IsStrCode(inst._imagename:value()) and ResolveStrCode(SubStrCode(inst._imagename:value())) or inst._imagename:value() })
        or STRINGS.NAMES.MINISIGN
end

local function minisign_postinit(inst)
    inst.displaynamefn = minisign_displaynamefn
end

local minisigns = {
    "minisign",
    "minisign_drawn",
}

for _, sign in ipairs(minisigns) do
    AddPrefabPostInit(sign, minisign_postinit)
end

require("components/drawingtool")
ACTIONS.DRAW.stroverridefn = function(act)
    local item = FindEntityToDraw(act.target, act.invobject)
    local drawnameoverride = item and item.drawnameoverride
    return item ~= nil
        and subfmt(STRINGS.ACTIONS.DRAWITEM,
                { item = drawnameoverride
                    and (IsStrCode(drawnameoverride) and ResolveStrCode(SubStrCode(drawnameoverride)) or drawnameoverride)
                    or item:GetBasicDisplayName() })
        or nil
end

local function common_drawnameoverride_fn(inst)
    local name = inst.nameoverride or inst.prefab
    inst.drawnameoverride = inst.drawnameoverride or EncodeStrCode({content = "NAMES." .. string.upper(name)})
end

local function spicedfoods_drawnameoverride_fn(inst)
    local spicename = string.gsub(inst.prefab, (inst.nameoverride or "") .. "_", "")
    spicename = string.upper(spicename)
    local drawnameoverride = {
        strtype = "subfmt",
        content = "NAMES." .. spicename .. "_FOOD",
        params = {
            food = STRCODE_HEADER .. "NAMES." .. string.upper(inst.nameoverride)
        }
    }
    -- subfmt(STRINGS.NAMES[data.spice.."_FOOD"], { food = STRINGS.NAMES[string.upper(inst.nameoverride)] })
    inst.drawnameoverride = inst.drawnameoverride or EncodeStrCode(drawnameoverride)
end

local function add_drawname_override(inst)

    if not TheWorld.ismastersim then return end

    if inst:HasTag("_inventoryitem")
    and not (inst:HasTag("INLIMBO") or inst:HasTag("notdrawable"))
    and inst.displaynamefn == nil
    and inst.name_author_netid == nil
    then
        inst:DoTaskInTime(0, common_drawnameoverride_fn)
    end

    if inst:HasTag("spicedfood") then
        inst:DoTaskInTime(0, spicedfoods_drawnameoverride_fn)
    end

end

AddPrefabPostInitAny(add_drawname_override)



--------------------------------------------------------------------------------
------------------------------------ SKETCH ------------------------------------
--------------------------------------------------------------------------------

local SKETCHES =
{
    { item = "chesspiece_pawn",         recipe = "chesspiece_pawn_builder" },
    { item = "chesspiece_rook",         recipe = "chesspiece_rook_builder" },
    { item = "chesspiece_knight",       recipe = "chesspiece_knight_builder" },
    { item = "chesspiece_bishop",       recipe = "chesspiece_bishop_builder" },
    { item = "chesspiece_muse",         recipe = "chesspiece_muse_builder" },
    { item = "chesspiece_formal",       recipe = "chesspiece_formal_builder" },
    { item = "chesspiece_deerclops",    recipe = "chesspiece_deerclops_builder" },
    { item = "chesspiece_bearger",      recipe = "chesspiece_bearger_builder" },
    { item = "chesspiece_moosegoose",   recipe = "chesspiece_moosegoose_builder" },
    { item = "chesspiece_dragonfly",    recipe = "chesspiece_dragonfly_builder" },
    { item = "chesspiece_clayhound",    recipe = "chesspiece_clayhound_builder",    image = "chesspiece_clayhound_sketch" },
    { item = "chesspiece_claywarg",     recipe = "chesspiece_claywarg_builder",     image = "chesspiece_claywarg_sketch" },
    { item = "chesspiece_butterfly",    recipe = "chesspiece_butterfly_builder",    image = "chesspiece_butterfly_sketch" },
    { item = "chesspiece_anchor",       recipe = "chesspiece_anchor_builder",       image = "chesspiece_anchor_sketch" },
    { item = "chesspiece_moon",         recipe = "chesspiece_moon_builder",         image = "chesspiece_moon_sketch" },
    { item = "chesspiece_carrat",       recipe = "chesspiece_carrat_builder",       image = "chesspiece_carrat_sketch" },
    { item = "chesspiece_malbatross",   recipe = "chesspiece_malbatross_builder" },
    { item = "chesspiece_crabking",     recipe = "chesspiece_crabking_builder" },
    { item = "chesspiece_toadstool",    recipe = "chesspiece_toadstool_builder" },
    { item = "chesspiece_stalker",      recipe = "chesspiece_stalker_builder" },
    { item = "chesspiece_klaus",        recipe = "chesspiece_klaus_builder" },
    { item = "chesspiece_beequeen",     recipe = "chesspiece_beequeen_builder" },
    { item = "chesspiece_antlion",      recipe = "chesspiece_antlion_builder" },
    { item = "chesspiece_minotaur",     recipe = "chesspiece_minotaur_builder" },
    { item = "chesspiece_beefalo",      recipe = "chesspiece_beefalo_builder",      image = "chesspiece_beefalo_sketch" },
    { item = "chesspiece_guardianphase3", recipe = "chesspiece_guardianphase3_builder", image = "chesspiece_guardianphase3_sketch" },
    { item = "chesspiece_eyeofterror",	recipe = "chesspiece_eyeofterror_builder" },
    { item = "chesspiece_twinsofterror", recipe = "chesspiece_twinsofterror_builder" },

}

local function get_sketch_string_fn(inst)
    local ret = {
        strtype = "subfmt",
        content = "NAMES.SKETCH",
        params = {
            item = STRCODE_HEADER .. "NAMES." .. string.upper(SKETCHES[inst.sketchid].recipe)
        }
    }

    return EncodeStrCode(ret)
end

local function sketch_postinit(inst)
    if not TheWorld.ismastersim then return end

    inst.components.named:SetName(get_sketch_string_fn(inst))

    local onload = inst.OnLoad
    inst.OnLoad = function(inst, data)
        onload(inst, data)
        inst.components.named:SetName(get_sketch_string_fn(inst))
        inst.drawnameoverride = get_sketch_string_fn(inst)
    end

    inst.drawnameoverride = get_sketch_string_fn(inst)
end

AddPrefabPostInit("sketch", sketch_postinit)

--------------------------------------------------------------------------------
--------------------------------- TACKLESKETCH ---------------------------------
--------------------------------------------------------------------------------

local TACKLESKETCHES =
{
	{ item = "oceanfishingbobber_ball",				recipe = "oceanfishingbobber_ball" },
	{ item = "oceanfishingbobber_oval",				recipe = "oceanfishingbobber_oval" },
	{ item = "oceanfishingbobber_crow",				recipe = "oceanfishingbobber_crow" },
	{ item = "oceanfishingbobber_robin",			recipe = "oceanfishingbobber_robin" },
	{ item = "oceanfishingbobber_robin_winter",		recipe = "oceanfishingbobber_robin_winter" },
	{ item = "oceanfishingbobber_canary",			recipe = "oceanfishingbobber_canary" },
	{ item = "oceanfishingbobber_goose",			recipe = "oceanfishingbobber_goose" },
	{ item = "oceanfishingbobber_malbatross",		recipe = "oceanfishingbobber_malbatross" },
    { item = "oceanfishinglure_hermit_drowsy",      recipe = "oceanfishinglure_hermit_drowsy" },
    { item = "oceanfishinglure_hermit_rain",        recipe = "oceanfishinglure_hermit_rain" },
    { item = "oceanfishinglure_hermit_heavy",       recipe = "oceanfishinglure_hermit_heavy" },
    { item = "oceanfishinglure_hermit_snow",        recipe = "oceanfishinglure_hermit_snow" },
}

local function get_tacklesketch_string_fn(inst)
    local ret = {
        strtype = "subfmt",
        content = "NAMES.TACKLESKETCH",
        params = {
            item = STRCODE_HEADER .. "NAMES." .. string.upper(TACKLESKETCHES[inst.sketchid].recipe)
        }
    }

    return EncodeStrCode(ret)
end

local function tacklesketch_postinit(inst)
    if not TheWorld.ismastersim then return end

    inst.components.named:SetName(get_tacklesketch_string_fn(inst))

    local onload = inst.OnLoad
    inst.OnLoad = function(inst, data)
        onload(inst, data)
        inst.components.named:SetName(get_tacklesketch_string_fn(inst))
        inst.drawnameoverride = get_tacklesketch_string_fn(inst)
    end

    inst.drawnameoverride = get_tacklesketch_string_fn(inst)
end

AddPrefabPostInit("tacklesketch", tacklesketch_postinit)

--------------------------------------------------------------------------------
-------------------------------- POSSIBLENAMES ---------------------------------
--------------------------------------------------------------------------------

local function rename_possiblenames(inst)
    inst.components.named:PickNewName()
end

local function insert_possiblenames(table, index, strcode)
    if table and #table > 0 then
        local lenth = #table
        STRCODE_POSSIBLENAMES[index] = STRCODE_POSSIBLENAMES[index] or {}
        for i = 1, lenth do
            STRCODE_POSSIBLENAMES[index][table[i]] = STRCODE_POSSIBLENAMES[index][table[i]] or {}
            STRCODE_POSSIBLENAMES[index][table[i]][#STRCODE_POSSIBLENAMES[index][table[i]] + 1] = strcode .. tostring(i)
        end
    end
end

local possiblenames_prefabs = {
    -- ["mooseegg"] = {"NAMES.MOOSEEGG", "NAMES.MOOSENEST"},
    ["moose"] = "NAMES.MOOSE",
    ["bunnyman"] = "BUNNYMANNAMES.",
    ["carnival_crowkid"] = "CROWNAMES.",
    ["pigman"] = "PIGNAMES.",
    ["pigguard"] = "PIGNAMES.",
    ["moonpig"] = "PIGNAMES.",
}

local function do_possiblenames_postinit(prefab, strcode, override_table)
    AddPrefabPostInit(prefab, function(inst)
        if not TheWorld.ismastersim then
            return
        end

        insert_possiblenames(override_table or inst.components.named.possiblenames, prefab, strcode)
        rename_possiblenames(inst)

        local onload = inst.OnLoad
        inst.OnLoad = function(inst, data)
            if onload then onload(inst, data) end
            rename_possiblenames(inst)
        end

    end)
end

for prefab, strcode in pairs(possiblenames_prefabs) do
    do_possiblenames_postinit(prefab, strcode)
end

-- local override_moose_strings
scheduler:ExecuteInTime(0, function()
    local moose_languages = {"zh", "zht", "chs"}
    for i = 1, #moose_languages do
        if LanguageTranslator.defaultlang == moose_languages[i] then
            STRINGS.NAMES.MOOSE1        = "麋鹿鸭"
            STRINGS.NAMES.MOOSE2        = "麋鹿鹅"
            STRINGS.NAMES.MOOSEEGG1     = "麋鹿鸭蛋"
            STRINGS.NAMES.MOOSEEGG2     = "麋鹿鹅蛋"
            STRINGS.NAMES.MOOSENEST1    = "麋鹿鸭巢"
            STRINGS.NAMES.MOOSENEST2    = "麋鹿鹅巢"
            -- print("Moose Strings Hack!")
        end
    end
end)

do_possiblenames_postinit("mooseegg", "NAMES.MOOSEEGG", {STRINGS.NAMES["MOOSEEGG1"], STRINGS.NAMES["MOOSEEGG2"]})
do_possiblenames_postinit("mooseegg", "NAMES.MOOSENEST", {STRINGS.NAMES["MOOSENEST1"], STRINGS.NAMES["MOOSENEST2"]})

-- Fix string hack after loading.
AddPrefabPostInit("mooseegg", function(inst)
    if not TheWorld.ismastersim then return end
    local onloadpostpass = inst.OnLoadPostPass
    inst.OnLoadPostPass = function(inst, ents, data, ...)
        if onloadpostpass then
            onloadpostpass(inst, ents, data, ...)
        end
        if data.has_egg and not data.EggHatched then
            if inst.components.timer:TimerExists("HatchTimer") then
                inst:DoTaskInTime(3 * FRAMES, function(inst)
                    inst.components.named.possiblenames = {STRINGS.NAMES["MOOSEEGG1"], STRINGS.NAMES["MOOSEEGG2"]}
                    rename_possiblenames(inst)
                end)
            end
        else
            inst:DoTaskInTime(3 * FRAMES, function(inst)
                inst.components.named.possiblenames = {STRINGS.NAMES["MOOSENEST1"], STRINGS.NAMES["MOOSENEST2"]}
                rename_possiblenames(inst)
            end)
        end
    end
end)


AddPrefabPostInit("moose", function(inst)
    if not TheWorld.ismastersim then return end
    inst:DoTaskInTime(3 * FRAMES, function(inst)
        inst.components.named.possiblenames = {STRINGS.NAMES["MOOSE1"], STRINGS.NAMES["MOOSE2"]}
        rename_possiblenames(inst)
    end)
end)
