local AddRecipe = AddRecipe
GLOBAL.setfenv(1, GLOBAL)

AddRecipe("propsign",
{ Ingredient("log", 2) },
RECIPETABS.MAGIC, TECH.MAGIC_THREE)

STRINGS.NAMES.PROPSIGN = "Prop Sign"
STRINGS.RECIPE_DESC.PROPSIGN = STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOMESIGN.GENERIC
